graph TD
    %% Stile dei nodi
    classDef selector fill:#f96,stroke:#333,stroke-width:2px,color:black;
    classDef sequence fill:#69f,stroke:#333,stroke-width:2px,color:white;
    classDef condition fill:#ff9,stroke:#333,stroke-width:1px,color:black,stroke-dasharray: 5 5;
    classDef action fill:#9f9,stroke:#333,stroke-width:1px,color:black;
    classDef wait fill:#f9f,stroke:#333,stroke-width:1px,color:black;

    %% ROOT
    Root[<h1><b>?</b></h1> Root Selector]:::selector
    Root --> ControlloDatiRedisSeq
    Root --> SafetySeq
    Root --> BatterySeq
    Root --> MissionSel

    %% RAMO 0: CONTROLLO DATI PRONTI DA REDIS -Altrimenti impedisco all'albero di andare avanti
    ControlloDatiRedisSeq[<h1><b>--></b></h1><b>Sequenza</b>: Controllo Dati Redis]:::sequence
    ControlloDatiRedisSeq --> ControlloDatiRedisSerHasRedisDataNotReady{Cond: Dati Redis Non Pronti?}:::condition
    ControlloDatiRedisSeq --> WaitRedis[Az: Wait 1 second]:::action

    %% RAMO 1: SICUREZZA (Safety) - Aggiornato con Wait
    SafetySeq[<h1><b>--></b></h1><b>Sequenza</b>: Sicurezza Persona]:::sequence
    SafetySeq --> IsPerson{Cond: Persona Rilevata?}:::condition
    SafetySeq --> Stop[Az: STOP Motori]:::action
    SafetySeq --> Wait5[Az: Wait 5 seconds]:::action
    
    %% RAMO 2: ENERGIA (Energy) - Aggiornato con Navigazione
    BatterySeq[<h1><b>--></b></h1><b>Sequenza</b>: Gestione Energia]:::sequence
    BatterySeq --> IsLowBat{Cond: Batteria sotto 20?}:::condition
    BatterySeq --> PlanCharge[Az: Calcola Percorso Ricarica]:::action
    BatterySeq --> MoveToCharge[Az: Vai al Punto di Ricarica]:::action
    BatterySeq --> Dock[Az: Ricarica]:::action

    %% RAMO 3: MISSIONE (Mission) - NUOVA LOGICA GRAFO
    MissionSel[<h1><b>?</b></h1><b>Selector</b>: Gestione Missione]:::selector
    
    

    %% 3.2 Pianificazione (Se manca il piano)
    MissionSel --> PlanningSeq[<h1><b>--></b></h1><b>Seq</b>: Generazione Piano]:::sequence
    PlanningSeq --> IsPlanMissing{Cond: Piano Non Calcolato? <br>Se la missione è finita il piano risulterà vuoto, bisognerà calcolare il percorso per andare a base ricarica}:::condition
    PlanningSeq --> GetMissionData[Az: Ricevi Lista & Priorità. <br>Se la missione è finita restituirà success senza prendere nulla]:::action
    PlanningSeq --> ComputeGraph[Az: Calcola Percorso Ottimizzato. <br>Se missione è conclusa la calcola per base ricarica]:::action

    %% 3.3 Esecuzione (Se ho il piano)
    MissionSel --> ExecuteSeq[<h1><b>--></b></h1><b>Seq</b>: Esecuzione Step]:::sequence
    
    %% A. Generazione Percorso per il Nodo Target
    ExecuteSeq --> PathSel[<h1><b>?</b></h1><b>Selector</b>: Generazione Percorso]:::selector
    ExecuteSeq --> MoveNode[Az: Vai al target]:::action
    PathSel --> IsPathCalculated{Cond: Il percorso è stato calcolato?}:::condition
    PathSel --> CalculatePath[Az: Calcola percorso]:::action

    
    
    %% B. Operazione sul Nodo (Picking o Delivery)
    ExecuteSeq --> ActionSel[<h1><b>?</b></h1><b>Selector</b>: Operazione Nodo]:::selector
    
    %% Ritiro
    ActionSel --> PickupSeq[<h1><b>--></b></h1><b>Seq</b>: Ritiro]:::sequence
    PickupSeq --> IsPickupNode{Cond: È Nodo Ritiro?}:::condition
    PickupSeq --> ExecPick[Az: Esegui Picking]:::action
    
    %% Consegna
    ActionSel --> DropSeq[<h1><b>--></b></h1><b>Seq</b>: Consegna]:::sequence
    DropSeq --> IsDropNode{Cond: È Nodo Consegna?}:::condition
    DropSeq --> ExecDrop[Az: Esegui Rilascio]:::action

